### ISSUE TITLE
Delete this feature please!

### ISSUE THREAD

**Issue by mjpikat** [RickWieman/stripboard#1]
(delete this feature please)

**Comment by RickWieman** [comment]
What do you mean exactly? That multiple users can share the same strip board, or that changes in EuroScope are directly reflected on the strip board?

**Comment by mjpikat** [comment]
Yep, so that multiple users can share one stripboard.

**Comment by RickWieman** [comment]
If I'm not mistaken, every controller normally has his own strip board. The idea behind this system is that, in the future, users can hand over strips, just like it happens in real life (e.g., the ground controller hands his strips over to the tower controller and vice versa).
I don't feel the need to implement layout sharing for the strip boards of the controllers through a database, just because those boards are controller specific and it doesn't make sense to have other controllers mess with my layout while I'm controlling.
It'll also be a bit of a hassle to have that working in realtime, not to mention the hassle to store and retrieve the layout in/from a database. But feel free to open a PR :wink:

**Comment by mjpikat** [comment]
Allright, thanks Rick for the heads up! I got your idea :+1:

**Comment by RickWieman** [comment]
You could have just closed the issue with a simple remark instead of removing all your content/comments :wink:
